### ISSUE TITLE
Ruby 2 support

### ISSUE THREAD

**Issue by ryansch** [nixme/jazz_hands#11]
Have you considered byebug and pry-byebug for ruby 2 support?  Would you accept a pull request in that direction?

**Comment by nixme** [comment]
Byebug only supports 2.0 and not 1.9. So that would trade support one for the other. I maintain pry-debugger too, so I've been hoping for debugger to just get support for 2.0 so we can support it all.

**Comment by ryansch** [comment]
Me too.

**Comment by nixme** [comment]
Closing in favor of #12, as _this_ gem itself does support Ruby 2.
