### ISSUE TITLE
Include awesome_print 1.2.0 html fixes

### ISSUE THREAD

**Issue by simple10** [nixme/jazz_hands#14]
awesome_print 1.2.0 introduced some important html formatting fixes for ActionView. Without these fixes, output is hard to read.

https://github.com/michaeldv/awesome_print/commit/ba7ff0fdcc6521e34ce21e1bef643776f34462ed

Please include 1.2.0. Thanks!

It's also nice to loosen up the dependencies a bit to allow for automatic upgrades. At least for the non-C extension gems.

**Comment by nixme** [comment]
Just pushed up 0.5.2 which upgrades to 1.2 and also loosens the dependency. Thanks!
