### ISSUE TITLE
Cannot use gem

### ISSUE THREAD

**Issue by Silex** [nixme/jazz_hands#15]
Hi,

I would like to have tried the gem but:

```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    jazz_hands (>= 0) ruby depends on
      railties (~> 3.0) ruby

    sass-rails (~> 4.0.0) ruby depends on
      railties (4.0.0)

Bundler could not find compatible versions for gem "coderay":
  In Gemfile:
    jazz_hands (>= 0) ruby depends on
      coderay (~> 0.9.8) ruby

    better_errors (>= 0) ruby depends on
      coderay (1.1.0)
```

Any idea about how to fix those?

**Comment by nixme** [comment]
Seems loosening the coderay dependency would help. Hold on, I'm going bump dependencies on the master branch.

**Comment by nixme** [comment]
I just pushed up 0.5.2. Give it a shot?

**Comment by Silex** [comment]
```
Bundler could not find compatible versions for gem "coderay":
  In Gemfile:
    jazz_hands (>= 0) ruby depends on
      coderay (~> 1.0.5) ruby

    better_errors (>= 0) ruby depends on
      coderay (1.1.0)
```

Maybe the issue is with the `better_errors` gem?

**Comment by nixme** [comment]
I'm guessing you have `better_errors` locked to an old version or git path? I can't seem to find a better_errors at http://rubygems.org/gems/better_errors that depends on coderay 1.1?

Try running `bundle update better_errors`. Or gist your whole Gemfile and Gemfile.lock so I can take a look?

**Comment by Silex** [comment]
Hum, for some reason my Gemfile.lock was indeed locking better_errors to an old version. Deleting it and typing bundle again fixed it! Thanks
