### ISSUE TITLE
Problem with dependencies in Rails 4.0.1

### ISSUE THREAD

**Issue by fluxusfrequency** [nixme/jazz_hands#16]
Hi,

I'm trying to get jazz_hands working on a Rails 4.0.1 project, but am getting this error:

Installing debugger (1.6.2)
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

```
/Users/benlewis/.rvm/rubies/ruby-2.0.0-p247/bin/ruby extconf.rb
```

**\* extconf.rb failed ***

...

An error occurred while installing debugger (1.6.2), and Bundler cannot continue.
Make sure that `gem install debugger -v '1.6.2'` succeeds before bundling.

**Comment by nixme** [comment]
Seems like an issue with the `debugger` gem not being able to recompile it's native extensions?

Have you upgraded to Mavericks but didn't recompile your ruby?

**Comment by fluxusfrequency** [comment]
Hmm, I tried recompiling, but it didn't change anything. Any other ideas? Thanks!

**Comment by nixme** [comment]
Does running `gem install debugger -v '1.6.2'` work? If it doesn't, then this is an issue for the debugger gem (a dependency), not this one. It would help if you posted the log file that usually follows that message "Results logged to ..."

**Comment by fluxusfrequency** [comment]
Hi,

Thanks for helping. It looks like it must be a debugger problem.

The log file reads:

``` bash
/Users/benlewis/.rvm/rubies/ruby-2.0.0-p247/bin/ruby extconf.rb 
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/benlewis/.rvm/rubies/ruby-2.0.0-p247/bin/ruby
/Users/benlewis/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:51:in `require': cannot load such file -- debugger/ruby_core_source (LoadError)
    from /Users/benlewis/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:51:in `require'
    from extconf.rb:16:in `<main>'
```

**Comment by fluxusfrequency** [comment]
Also, is this the pry-debugger, or ruby-debug gem?

**Comment by schaary** [comment]
I use Mavericks and rbenv to manage my ruby environment. I have no problems - only with pry itself. But that's a bug in pry-0.9.12.4.

**Comment by nixme** [comment]
debugger is the gem from https://github.com/cldwalker/debugger.

pry-debugger, this gem, is some glue between debugger and pry, the two upstream gems that provide the bulk of functionality.

**Comment by nixme** [comment]
Ah, I misread which project I'm managing. _This_ gem is jazz_hands, not pry-debugger. Anyhow, you might want to try the "bring-your-own-debugger" branch as mentioned in #12 to get jazz_hands working. Since you look to be using Ruby 2.0.0, just add pry-byebug to your Gemfile right after.

**Comment by fluxusfrequency** [comment]
Thanks! That worked like a charm!
