### ISSUE TITLE
Evaluate line by line with pry?

### ISSUE THREAD

**Issue by jmuheim** [nixme/jazz_hands#17]
Hey there

I have a lot of biiiig Capybara request specs:

``` ruby
it 'does something' do
  visit some_path

  do_something
  do_another_thing
  do_something_again
  do_do_do

  expect(page).to have_selector 'bla'
end
```

When one of it fails, it's often useful to use `driver: :chrome` to see what happens visually and set a binding.pry somewhere in the beginning:

``` ruby
it 'does something', driver: :chrome do
  visit some_path

  binding.pry
  do_something
  do_another_thing
  do_something_again
  do_do_do

  expect(page).to have_selector 'bla'
end
```

Now I'd like to see step by step what Capybara is doing, so I intuitively want to use `s` or `n`. But instead of executing line by line, it always jumps into some Capybara methods which I'm actually not interested in. I searched a lot and I found different gems claiming to do something like that, but none seems to do the job as I need it.

So I wanted to ask you (because you seem to know many pry gems in and out): is there a solution for my need? Or is it simply not possible?

Thank you.

**Comment by nixme** [comment]
This is a bug with debugger and MRI 2.0. See https://github.com/nixme/pry-debugger/issues/34

Closing as that bug, plus the upstream debugger bug cover all this. jazz_hands doesn't implement step or next itself.
