### ISSUE TITLE
Replace pry-debugger with pry-byebug

### ISSUE THREAD

**Issue by jmuheim** [nixme/jazz_hands#23]
It seems that pry-byebug is the successor of pry-debugger. It seems to fix the "next erroneously behaves like step" bug:

https://github.com/nixme/pry-debugger/issues/34#issuecomment-36779480

You should consider to replace pry-debugger.

**Comment by nixme** [comment]
The next version of jazz_hands probably won't include a debugger so ppl can chose whichever one they want depending on environment: pry-byebug for mri2+, pry-nav for jruby, pry-debugger for old mri. See #12 where a new branch has already been created for that.

You can use it in your `Gemfile`:

``` ruby
gem 'jazz_hands', github: 'nixme/jazz_hands', branch: 'bring-your-own-debugger'
gem 'pry-byebug'
```

**Comment by jmuheim** [comment]
Thank you!

**Comment by fbernier** [comment]
@nixme I know you must not have much time for this but the release you talked in other issued with #13 and this would be very handy. If you're looking for help maintaining this I am willing.

**Comment by jeremyhaile** [comment]
@nixme shouldn't this issue still be open until the changes you mentioned about removing pry-debugger from the dependencies is done. This would be useful for me tracking this so I know when we can switch back to the release version.

As it stands, the bring-your-own-debugger depends on outdated pry versions, whereas master has been updated.

**Comment by plribeiro3000** [comment]
@jeremyhaile take a look at my fork. [plribeiro3000/jazz_fingers](https://github.com/plribeiro3000/jazz_fingers). it has updated versions os the dependencies.

**Comment by jeremyhaile** [comment]
@plribeiro3000 Thanks. I'll use your fork for now, although I'd love to see the official version get updated. 

Have you submitted a pull request?

**Comment by plribeiro3000** [comment]
Nope. There are a lot of open PR's already. I've opened a new issue to ask
about the project but i got no answer so i forked. See #32 .

Em dom, 22 de fev de 2015 17:26, Jeremy Haile notifications@github.com
escreveu:
