### ISSUE TITLE
No colours when running with spring

### ISSUE THREAD

**Issue by michalmuskala** [nixme/jazz_hands#24]
When rails console is initialized with spring binstubs there are no colours.
With bin/rails like that:

``` ruby
#!/usr/bin/env ruby
# begin
#   load File.expand_path("../spring", __FILE__)
# rescue LoadError
# end
APP_PATH = File.expand_path('../../config/application',  __FILE__)
require_relative '../config/boot'
require 'rails/commands'
```

running `bin/rails console` I get:
![1](https://f.cloud.github.com/assets/477062/2398743/99950648-a9f8-11e3-9fd7-fb381793d0e2.png)

With bin/rails like that:

``` ruby
#!/usr/bin/env ruby
begin
  load File.expand_path("../spring", __FILE__)
rescue LoadError
end
APP_PATH = File.expand_path('../../config/application',  __FILE__)
require_relative '../config/boot'
require 'rails/commands'
```

running `bin/rails console` I get:
![2](https://f.cloud.github.com/assets/477062/2398760/bf956d7e-a9f8-11e3-8dd5-6ecd9010bf37.png)

**Comment by nixme** [comment]
Interesting, works fine for me using spring.

jazz_hands detects colors via `Readline::VERSION`. Can you see what that evaluates to in a spring and non-spring context?

**Comment by michalmuskala** [comment]
I've checked today again and it's totally fine. Probably fixed by system reboot. I'm really sorry for bothering you.
BTW. You're doing great job with jazz_hands - it's awesome, we're using it in all our projects.
