### ISSUE TITLE
Activity

### ISSUE THREAD

**Issue by plribeiro3000** [nixme/jazz_hands#32]
Is this project dead?
- The last release was 1 year ago
- There are opened pull requests and people willing to improve/use it

We need at least to update the dependencies over here and fix the debugger thing.
I can create a pull request to update the dependencies only and another to remove any dependency on debuggers as mentioned [here](https://github.com/nixme/jazz_hands/pull/26#issuecomment-43928370). 

cc/ @nixme

**Comment by plribeiro3000** [comment]
I guess would be better to maintain a fork since there is no answer to this. =s

**Comment by plribeiro3000** [comment]
For those who wants support. I just released the code with a few changes, mostly grabbed from open pull requests and released as [`jazz_fingers`](https://rubygems.org/gems/jazz_fingers).

Any issues/concerns, please let me know!

@nixme If you want we can talk about it. :smile:

**Comment by nixme** [comment]
Hey @plribeiro3000, I just haven't had a proper break to look at issues and work on these projects, but I have some more time now. I'll be taking a look over Thanksgiving and cleaning up issues. Feel free to message me separately if you want or comment on this thread. Thanks!

**Comment by plribeiro3000** [comment]
:+1:

**Comment by jeremyhaile** [comment]
@nixme Would it be better to give @plribeiro3000 commit access so that we don't have two forks being maintained of this project?

**Comment by jeremyhaile** [comment]
(trying to decide whether to switch to jazz_fingers or if this project will ever get updated again.
