### ISSUE TITLE
cannot install jazz_hands with Ruby 2.1.4  needs debugger which is still incompatible

### ISSUE THREAD

**Issue by ghost** [nixme/jazz_hands#34]
I am on my way to upgrade a rails app from rails 3 to rails 4/ruby2.1.4 , if I try to use the jazz_hands gem , the bundle install fails ... trying to install the gem 'debugger -v '1.6.8' which is incompatible with ruby 2.1

when I comment the gem 'jazz_hands' then bundle install succeed ...

any clue ?

**Comment by Rojo** [comment]
@erwin Follow this to get jazz_hands to work on ruby 2.1.x: https://github.com/nixme/jazz_hands/issues/25#issuecomment-43281752

**Comment by h35514n** [comment]
Hi all, 

Just a head's up that I have an updated (Ruby 2-compatible) fork of the gem [here](https://github.com/jkrmr/jazz_hands), which you can install using 

``` ruby
group :development, :test do
  gem 'jazz_hands', github: 'jkrmr/jazz_hands'
end
```

or, if you're not using bundler,

``` bash
$ gem install specific_install
$ gem specific_install jkrmr/jazz_hands
```

Hopefully this'll relieve some headaches. Cheers :)

**Comment by ghost** [comment]
thanks .. bundling correctly w ruby 2.1.4 ...

**Comment by plribeiro3000** [comment]
You can give [`jazz_fingers`](http://github.com/plribeiro3000/jazz_fingers) a try. It is a fork with updates and released with another name so you won't need to use github to pull the code.

**Comment by skull-squadron** [comment]
[`jazz_fingers`](https://github.com/plribeiro3000/jazz_fingers) FTW
