### ISSUE TITLE
TIme for another `bundle update` (or equivalent)?

### ISSUE THREAD

**Issue by mattscilipoti** [nixme/jazz_hands#4]
It's been 6 months since the last upgrade.  I removed the version limiters in the .gempec and ran a `bundle update`.  Everything seems to be working.  No errors yet. 

Since jazz_hands is mostly a wrapper around other gems, I recommend using gemnasium.  They alert me when my gems are "out of date" (e.g. https://gemnasium.com/mattscilipoti/jazz_hands).

**Comment by nixme** [comment]
Just pushed a version 0.4 that updates the dependent gem and includes some other bug fixes. Thanks for the gemnasium recommendation.
