### ISSUE TITLE
Colored prompt and extra symbols

### ISSUE THREAD

**Issue by ineu** [nixme/jazz_hands#5]
In default `rails console` without any extra settings prompt contains extra symbols, but only when displaying result of the command (when typing command current prompt is ok)
![2013-01-21_22-40-39](https://f.cloud.github.com/assets/24980/84341/e556ae4a-640a-11e2-9ac3-98f424340fb4.png)

**Comment by nixme** [comment]
For a quick workaround, disable the colored prompt in an initializer:

``` ruby
JazzHands.colored_prompt = false
```

**Comment by nixme** [comment]
So I believe the issue here is the `\001` and `\002` characters I'm inserting to keep readline history working with a colored prompt (see http://stackoverflow.com/questions/8806643/colorized-output-breaks-linewrapping-with-readline for details).

Most fonts should just not display anything for them. If you change your terminal font, does it help?

**Comment by ineu** [comment]
Virtual console with UniCyr font is ok, as well as rxvt/urxvt, konsole and xterm. Problem encountered in xfce4-terminal and gnome-terminal.

**Comment by ineu** [comment]
Ok, the problem is in pry: indent.rb#corrent_indentation. This method overwrites readline's input line with it's own indented version. Readline doesn't display \001 and \002 in input, but IO#print displays it. rxvt and friends just ignore such symbols, but xfce4-terminal and gnome-terminal try to display it.

**Comment by ineu** [comment]
Fixed in pry 0.9.12, closing.

**Comment by mjc** [comment]
This is occurring again with pry 0.9.12, jazz_hands 0.5.1, and gnome_terminal 3.6.1.

**Comment by nixme** [comment]
@mjc, I'm assuming because you're using gnome_terminal that you're on linux with a ruby compiled against GNU readline? 

Can you tell me what the following statements return inside the console?

``` ruby
Readline::VERSION
```

and

``` ruby
defined?(RbReadline)
```

A temporary workaround is setting `JazzHands.colored_prompt = false` as mentioned above.

**Comment by mjc** [comment]
`Readline::VERSION` is 6.2, RbReadline isn't loaded.  Also this is Ruby 2.0.0-p247.  I did disable it in my initializer temporarily but I was hoping to help squash the bug.  :)

**Comment by nixme** [comment]
a screenshot would help. I'll need to set up a VM to test. Are you using Ubuntu? And what version of gnome_terminal? Does changing the terminal font help?
